const int SNAIL_RENDER_ABI_VERSION = 1;

const int SNAIL_SPECIAL_LAYER_SENTINEL = 255;
const int SNAIL_SPECIAL_KIND_COLR = 0;
const int SNAIL_SPECIAL_KIND_PATH = 1;
const int SNAIL_SPECIAL_KIND_HINTED_TEXT = 2;
const int SNAIL_SPECIAL_KIND_AUTOHINT = 3;

const int SNAIL_PAINT_KIND_SOLID = 1;
const int SNAIL_PAINT_KIND_LINEAR_GRADIENT = 2;
const int SNAIL_PAINT_KIND_RADIAL_GRADIENT = 3;
const int SNAIL_PAINT_KIND_IMAGE = 4;
const int SNAIL_PAINT_KIND_COMPOSITE_GROUP = 5;
const int SNAIL_PAINT_KIND_CONIC_GRADIENT = 6;

const int SNAIL_PAINT_TEXELS_PER_RECORD = 6;
const int SNAIL_PATH_COMPOSITE_MODE_FILL_STROKE_INSIDE = 1;
