//! GENERATED by build/gen_shader_reflection_zig.zig from `slangc
//! -reflection-json` over the shared-parameter-block families — the
//! machine-derived parameter ABI. Committed to src/snail/shader/reflection.zig
//! so the shader binding contract is consumable without a shader toolchain;
//! `zig build check-reflection` fails if it drifts from the shaders. Do not
//! hand-edit: run `zig build gen-shaders` and commit the result. The data ABI
//! (instance-stream semantics, atlas texel layouts, blend semantics) is NOT
//! here — see src/snail/format/abi.zig and the emit/record contracts.

/// The per-draw parameter fields and offsets reflected from Vulkan.
pub const PushConstants = extern struct {
    mvp: [16]f32,
    viewport: [2]f32,
    subpixel_order: i32,
    output_srgb: i32,
    page_base: i32,
    coverage_exponent: f32,
    dither_scale: f32,
    mask_output: i32,
    atlas_page_texels: [2]i32,
};

comptime {
    if (@sizeOf(PushConstants) != 104) @compileError("PushConstants size drifted from reflection");
    if (@offsetOf(PushConstants, "mvp") != 0) @compileError("PushConstants.mvp offset drifted from reflection");
    if (@offsetOf(PushConstants, "viewport") != 64) @compileError("PushConstants.viewport offset drifted from reflection");
    if (@offsetOf(PushConstants, "subpixel_order") != 72) @compileError("PushConstants.subpixel_order offset drifted from reflection");
    if (@offsetOf(PushConstants, "output_srgb") != 76) @compileError("PushConstants.output_srgb offset drifted from reflection");
    if (@offsetOf(PushConstants, "page_base") != 80) @compileError("PushConstants.page_base offset drifted from reflection");
    if (@offsetOf(PushConstants, "coverage_exponent") != 84) @compileError("PushConstants.coverage_exponent offset drifted from reflection");
    if (@offsetOf(PushConstants, "dither_scale") != 88) @compileError("PushConstants.dither_scale offset drifted from reflection");
    if (@offsetOf(PushConstants, "mask_output") != 92) @compileError("PushConstants.mask_output offset drifted from reflection");
    if (@offsetOf(PushConstants, "atlas_page_texels") != 96) @compileError("PushConstants.atlas_page_texels offset drifted from reflection");
}

pub const vulkan_push_constant_size: u32 = 104;

/// Descriptor slots (Vulkan set-0 bindings; the canonical numbers the
/// other targets map in declaration order).
pub const binding = struct {
    pub const curve_tex: u32 = 0;
    pub const band_tex: u32 = 1;
    pub const layer_tex: u32 = 2;
    pub const image_tex: u32 = 3;
    pub const image_sampler: u32 = 3;
    /// WGSL: the parameter block is a uniform buffer at this group/binding.
    pub const wgsl_params_group: u32 = 2;
    pub const wgsl_params_binding: u32 = 0;
};
