/* snail - GPU font rendering via direct Bezier curve evaluation.
 *
 * C API model:
 *   - CPU values are owned handles: TextAtlas, ShapedText, TextBlob,
 *     TextBlobBuilder, Image, PathPicture, Scene, ResourceManifest,
 *     PreparedResources, PreparedScene.
 *   - Resource upload is explicit: build a ResourceManifest, upload it with a
 *     Renderer, then draw a PreparedScene.
 *   - Pass NULL for SnailAllocator to use libc malloc/free.
 *   - Allocator descriptors are copied at handle creation. The descriptor
 *     pointer may be temporary, but its ctx and callbacks must remain valid
 *     until all handles and derived snapshots using that allocator are
 *     destroyed.
 *
 * MIT License. */

#ifndef SNAIL_H
#define SNAIL_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* Generated by `zig build install` / `zig build generate-c-api`; not checked in. */
#include "snail_generated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Allocator */

/* `free_fn` receives the size and alignment originally requested through the
 * Zig allocator adapter. It may ignore either value when the backing allocator
 * does not require them. */
typedef void *(*SnailAllocFn)(void *ctx, size_t size, size_t alignment);
typedef void (*SnailFreeFn)(void *ctx, void *ptr, size_t size, size_t alignment);

typedef struct {
    SnailAllocFn alloc_fn;
    SnailFreeFn free_fn;
    void *ctx;
} SnailAllocator;

/* Value types */

typedef struct {
    float min_x, min_y, max_x, max_y;
} SnailBBox;

typedef struct {
    float x, y, w, h;
} SnailRect;

typedef struct {
    float data[16];
} SnailMat4;

typedef struct {
    const char *data;
    size_t len;
} SnailString;

typedef struct {
    float xx, xy, tx;
    float yx, yy, ty;
} SnailTransform2D;

#define SNAIL_TRANSFORM2D_IDENTITY ((SnailTransform2D){1, 0, 0, 0, 1, 0})

typedef struct {
    SnailTransform2D transform;
    float tint[4];
} SnailOverride;

#define SNAIL_OVERRIDE_IDENTITY ((SnailOverride){SNAIL_TRANSFORM2D_IDENTITY, {1, 1, 1, 1}})

typedef struct {
    size_t start;
    size_t count;
} SnailRange;

#define SNAIL_RANGE_ALL ((SnailRange){0, SIZE_MAX})

typedef struct {
    size_t shape_count;
} SnailShapeMark;

/* Opaque resource key value. Literal integers remain valid numeric keys and
 * round-trip through result APIs as the same integer. Named and derived keys
 * use the high bits internally; treat non-literal keys as opaque values. */
typedef uint64_t SnailResourceKey;

typedef struct {
    SnailResourceKey atlas_key;
    SnailResourceKey paint_key;
    bool has_paint_key;
} SnailTextResourceKeys;

typedef struct {
    const SnailTextBlob *blob;
    SnailTextResourceKeys resources;
    SnailOverride override_value;
    bool has_override;
} SnailTextDraw;

typedef struct {
    const SnailPathPicture *picture;
    SnailResourceKey key;
    SnailRange range;
    SnailOverride override_value;
    bool has_range;
    bool has_override;
} SnailPathPictureDraw;

typedef struct {
    uint64_t identity;
    uint64_t layout;
    uint64_t content;
} SnailResourceStamp;

#define SNAIL_RESOURCE_CAPACITY_GROWABLE 0
#define SNAIL_RESOURCE_CAPACITY_EXACT 1

typedef struct {
    size_t curve_bytes_used;
    size_t curve_bytes_allocated;
    size_t band_bytes_used;
    size_t band_bytes_allocated;
    size_t layer_info_bytes_used;
    size_t layer_info_bytes_allocated;
    size_t image_bytes_used;
    size_t image_bytes_allocated;
} SnailResourceFootprint;

typedef struct {
    uint64_t generation;
    uint32_t active_atlas_pages_resident;
    uint32_t active_atlas_layers_allocated;
    uint32_t atlas_pages_resident;
    uint32_t atlas_layers_allocated;
    uint32_t active_image_layers_resident;
    uint32_t active_image_layers_allocated;
    uint32_t image_layers_resident;
    uint32_t image_layers_allocated;
} SnailResourceCacheStats;

typedef struct {
    SnailResourceFootprint footprint;
    size_t upload_bytes;
    size_t upload_curve_bytes;
    size_t upload_band_bytes;
    size_t upload_layer_info_bytes;
    size_t upload_image_bytes;
    size_t changed_bytes;
    size_t changed_key_count;
    bool requires_cache_rebuild;
} SnailResourceUploadPlanSummary;

size_t snail_resource_footprint_used_bytes(SnailResourceFootprint footprint);
size_t snail_resource_footprint_allocated_bytes(SnailResourceFootprint footprint);
SnailResourceKey snail_resource_key_from_bytes(const char *data, size_t len);
SnailResourceKey snail_resource_key_from_cstr(const char *data);

typedef struct {
    uint16_t advance_width;
    int16_t lsb;
    SnailBBox bbox;
} SnailGlyphMetrics;

typedef struct {
    int16_t ascent, descent, line_gap;
} SnailLineMetrics;

typedef struct {
    int16_t underline_position;
    int16_t underline_thickness;
    int16_t strikethrough_position;
    int16_t strikethrough_thickness;
} SnailDecorationMetrics;

typedef struct {
    int16_t x_size;
    int16_t y_size;
    int16_t x_offset;
    int16_t y_offset;
} SnailScriptMetrics;

typedef struct {
    float x;
    float y;
    float font_size;
} SnailScriptTransform;

typedef struct {
    float cell_width, line_height;
} SnailCellMetrics;

typedef struct {
    float embolden;
    float skew_x;
} SnailSyntheticStyle;

typedef struct {
    const uint8_t *data;
    size_t len;
    int weight;
    bool italic;
    bool fallback;
    SnailSyntheticStyle synthetic;
} SnailFaceSpec;

typedef struct {
    int weight;
    bool italic;
} SnailFontStyle;

typedef struct {
    uint16_t face_index;
    uint16_t glyph_id;
    float x_offset, y_offset;
    float x_advance, y_advance;
    uint32_t source_start, source_end;
} SnailShapedGlyph;

typedef struct {
    float baseline_x, baseline_y;
    float em;
} SnailTextPlacement;

typedef struct {
    float pixel_width;
    float pixel_height;
    /* Explicit color encoding for this target.
     * attachment_encoding describes how the current attachment interprets
     * fragment outputs.
     *
     * stored_pixel_encoding describes the encoding expected in the final stored
     * pixels. For normal sRGB displays, both fields are
     * SNAIL_COLOR_ENCODING_SRGB. */
    int attachment_encoding;
    int stored_pixel_encoding;
} SnailTargetSurface;

typedef struct {
    int32_t x;
    int32_t y;
    uint32_t w;
    uint32_t h;
} SnailPixelRect;

typedef struct {
    int backdrop_kind;
    float clear_color[4];
    int region_kind;
    SnailPixelRect region_rect;
    int intermediate_format;
} SnailLinearResolve;

typedef struct {
    int subpixel_order;
    int fill_rule;
    /* Exponent applied to analytic coverage after edge evaluation.
     * 1.0 is identity; values below 1.0 strengthen antialiased edges and
     * values above 1.0 lighten them. */
    float coverage_exponent;
} SnailRasterOptions;

typedef struct {
    SnailMat4 mvp;
    SnailTargetSurface surface;
    SnailRasterOptions raster;
} SnailDrawState;

typedef struct {
    SnailDrawState state;
    int resolve_kind;
    SnailLinearResolve linear_resolve;
} SnailDrawPass;

typedef struct {
    int fill_rule;
    int subpixel_order;
    bool output_srgb;
    float coverage_exponent;
    uint32_t layer_base;
} SnailCoverageDrawState;

/* Enums */

#define SNAIL_FONT_WEIGHT_THIN 1
#define SNAIL_FONT_WEIGHT_EXTRA_LIGHT 2
#define SNAIL_FONT_WEIGHT_LIGHT 3
#define SNAIL_FONT_WEIGHT_REGULAR 4
#define SNAIL_FONT_WEIGHT_MEDIUM 5
#define SNAIL_FONT_WEIGHT_SEMI_BOLD 6
#define SNAIL_FONT_WEIGHT_BOLD 7
#define SNAIL_FONT_WEIGHT_EXTRA_BOLD 8
#define SNAIL_FONT_WEIGHT_BLACK 9

#define SNAIL_PAINT_SOLID 0
#define SNAIL_PAINT_LINEAR 1
#define SNAIL_PAINT_RADIAL 2
#define SNAIL_PAINT_IMAGE 3

#define SNAIL_COLOR_ENCODING_LINEAR 0
#define SNAIL_COLOR_ENCODING_SRGB 1
#define SNAIL_DRAW_RESOLVE_DIRECT 0
#define SNAIL_DRAW_RESOLVE_LINEAR 1
#define SNAIL_RESOLVE_BACKDROP_TARGET 0
#define SNAIL_RESOLVE_BACKDROP_CLEAR 1
#define SNAIL_RESOLVE_BACKDROP_TRANSPARENT 2
#define SNAIL_RESOLVE_BACKDROP_DONT_CARE 3
#define SNAIL_RESOLVE_REGION_FULL_TARGET 0
#define SNAIL_RESOLVE_REGION_PIXEL_RECT 1
#define SNAIL_INTERMEDIATE_FORMAT_RGBA16F 0
#define SNAIL_INTERMEDIATE_FORMAT_RGBA32F 1

#define SNAIL_EXTEND_CLAMP 0
#define SNAIL_EXTEND_REPEAT 1
#define SNAIL_EXTEND_REFLECT 2

#define SNAIL_IMAGE_FILTER_LINEAR 0
#define SNAIL_IMAGE_FILTER_NEAREST 1

#define SNAIL_CAP_BUTT 0
#define SNAIL_CAP_SQUARE 1
#define SNAIL_CAP_ROUND 2

#define SNAIL_JOIN_MITER 0
#define SNAIL_JOIN_BEVEL 1
#define SNAIL_JOIN_ROUND 2

#define SNAIL_STROKE_CENTER 0
#define SNAIL_STROKE_INSIDE 1

#define SNAIL_FILL_NONZERO 0
#define SNAIL_FILL_EVENODD 1

#define SNAIL_SUBPIXEL_NONE 0
#define SNAIL_SUBPIXEL_RGB 1
#define SNAIL_SUBPIXEL_BGR 2
#define SNAIL_SUBPIXEL_VRGB 3
#define SNAIL_SUBPIXEL_VBGR 4

#define SNAIL_DECORATION_UNDERLINE 0
#define SNAIL_DECORATION_STRIKETHROUGH 1

/* Paint / style types */

typedef struct {
    float start_x, start_y, end_x, end_y;
    float start_color[4], end_color[4];
    int extend;
} SnailLinearGradient;

typedef struct {
    float center_x, center_y, radius;
    float inner_color[4], outer_color[4];
    int extend;
} SnailRadialGradient;

typedef struct {
    const SnailImage *image;
    SnailTransform2D uv_transform;
    float tint[4];
    int extend_x, extend_y;
    int filter;
} SnailImagePaint;

typedef struct {
    int kind;
    float paint_solid[4];
    SnailLinearGradient paint_linear;
    SnailRadialGradient paint_radial;
    SnailImagePaint paint_image;
} SnailPaint;

typedef struct {
    SnailTextPlacement placement;
    SnailPaint fill;
} SnailTextAppendOptions;

typedef struct {
    float advance_x, advance_y;
    bool missing;
} SnailTextAppendResult;

typedef struct {
    uint32_t x_26_6;
    uint32_t y_26_6;
} SnailTrueTypeHintPpem;

typedef struct {
    size_t glyph_count;
    float advance_x, advance_y;
} SnailTrueTypeHintRunStats;

typedef struct {
    SnailPaint paint;
} SnailFillStyle;

typedef struct {
    SnailPaint paint;
    float width;
    int cap, join;
    float miter_limit;
    int placement;
} SnailStrokeStyle;

/* Font metrics helper */

int snail_font_init(const uint8_t *data, size_t len, SnailFont **out);
void snail_font_deinit(SnailFont *font);
uint16_t snail_font_units_per_em(const SnailFont *font);
uint16_t snail_font_glyph_index(const SnailFont *font, uint32_t codepoint);
int16_t snail_font_get_kerning(const SnailFont *font, uint16_t left, uint16_t right);
int snail_font_glyph_metrics(const SnailFont *font, uint16_t glyph_id, SnailGlyphMetrics *out);
int snail_font_line_metrics(const SnailFont *font, SnailLineMetrics *out);
int snail_font_decoration_metrics(const SnailFont *font,
                                  SnailDecorationMetrics *out);
int snail_font_superscript_metrics(const SnailFont *font,
                                   SnailScriptMetrics *out);
int snail_font_subscript_metrics(const SnailFont *font,
                                 SnailScriptMetrics *out);
int snail_font_advance_width(const SnailFont *font, uint16_t glyph_id, int16_t *out);
int snail_font_bbox(const SnailFont *font, uint16_t glyph_id, SnailBBox *out);

/* Text atlas, shaping, and text blobs */

int snail_text_atlas_init(const SnailAllocator *alloc,
                          const SnailFaceSpec *specs,
                          size_t spec_count,
                          SnailTextAtlas **out);
void snail_text_atlas_deinit(SnailTextAtlas *atlas);
size_t snail_text_atlas_page_count(const SnailTextAtlas *atlas);
void snail_text_atlas_upload_footprint(const SnailTextAtlas *atlas,
                                       SnailResourceFootprint *out);
size_t snail_text_atlas_texture_byte_len(const SnailTextAtlas *atlas);
int snail_text_atlas_units_per_em(const SnailTextAtlas *atlas, uint16_t *out);
int snail_text_atlas_line_metrics(const SnailTextAtlas *atlas, SnailLineMetrics *out);
size_t snail_text_atlas_face_count(const SnailTextAtlas *atlas);
int snail_text_atlas_primary_face_index(const SnailTextAtlas *atlas, uint16_t *out);
int snail_text_atlas_face_units_per_em(const SnailTextAtlas *atlas,
                                       size_t face_index,
                                       uint16_t *out);
int snail_text_atlas_face_line_metrics(const SnailTextAtlas *atlas,
                                       size_t face_index,
                                       SnailLineMetrics *out);
int snail_text_atlas_glyph_index(const SnailTextAtlas *atlas,
                                 size_t face_index,
                                 uint32_t codepoint,
                                 uint16_t *out);
int snail_text_atlas_advance_width(const SnailTextAtlas *atlas,
                                   size_t face_index,
                                   uint16_t glyph_id,
                                   int16_t *out);
int snail_text_atlas_cell_metrics(const SnailTextAtlas *atlas,
                                  SnailFontStyle style,
                                  float em,
                                  SnailCellMetrics *out);
int snail_text_atlas_measure_text(const SnailTextAtlas *atlas,
                                  SnailFontStyle style,
                                  const char *text,
                                  size_t text_len,
                                  float font_size,
                                  float *out);
int snail_text_atlas_decoration_rect(const SnailTextAtlas *atlas,
                                     int decoration,
                                     float x,
                                     float y,
                                     float advance,
                                     float font_size,
                                     SnailRect *out);
int snail_text_atlas_superscript_transform(const SnailTextAtlas *atlas,
                                           float x,
                                           float y,
                                           float font_size,
                                           SnailScriptTransform *out);
int snail_text_atlas_subscript_transform(const SnailTextAtlas *atlas,
                                         float x,
                                         float y,
                                         float font_size,
                                         SnailScriptTransform *out);
int snail_text_atlas_shape_utf8(const SnailTextAtlas *atlas,
                                SnailFontStyle style,
                                const char *text,
                                size_t text_len,
                                SnailShapedText **out);
int snail_text_atlas_ensure_text(const SnailTextAtlas *atlas,
                                 SnailFontStyle style,
                                 const char *text,
                                 size_t text_len,
                                 SnailTextAtlas **out);
int snail_text_atlas_ensure_shaped(const SnailTextAtlas *atlas,
                                   const SnailShapedText *shaped,
                                   SnailTextAtlas **out);
int snail_text_atlas_ensure_glyphs(const SnailTextAtlas *atlas,
                                   size_t face_index,
                                   const uint16_t *glyph_ids,
                                   size_t glyph_count,
                                   SnailTextAtlas **out);

void snail_shaped_text_deinit(SnailShapedText *shaped);
size_t snail_shaped_text_glyph_count(const SnailShapedText *shaped);
float snail_shaped_text_advance_x(const SnailShapedText *shaped);
float snail_shaped_text_advance_y(const SnailShapedText *shaped);
bool snail_shaped_text_glyph(const SnailShapedText *shaped, size_t index, SnailShapedGlyph *out);
size_t snail_shaped_text_copy_glyphs(const SnailShapedText *shaped,
                                     SnailShapedGlyph *out,
                                     size_t capacity);

int snail_text_blob_builder_init(const SnailAllocator *alloc,
                                 const SnailTextAtlas *atlas,
                                 SnailTextBlobBuilder **out);
void snail_text_blob_builder_deinit(SnailTextBlobBuilder *builder);
void snail_text_blob_builder_reset(SnailTextBlobBuilder *builder);
size_t snail_text_blob_builder_glyph_count(const SnailTextBlobBuilder *builder);
int snail_text_blob_builder_append_shaped(SnailTextBlobBuilder *builder,
                                          const SnailShapedText *shaped,
                                          SnailRange glyphs,
                                          SnailTextAppendOptions options,
                                          SnailTextAppendResult *out_result);
int snail_text_blob_builder_append_prepared_hinted_run(SnailTextBlobBuilder *builder,
                                                       const SnailTrueTypePreparedHintRun *run,
                                                       SnailTextPlacement placement,
                                                       const float color[4],
                                                       SnailTextAppendResult *out_result);
int snail_text_blob_builder_finish(SnailTextBlobBuilder *builder,
                                   SnailTextBlob **out);

/* Explicit TrueType hinting for grid-fitted small text. Prepared hint runs
 * borrow the hint context cache and atlas snapshot until appended or destroyed.
 * Functions return SNAIL_ERR_HINT_UNAVAILABLE when a font/glyph cannot be
 * represented as reusable hinted curve deltas; callers should fall back to the
 * normal unhinted text path. */
SnailTrueTypeHintPpem snail_true_type_hint_ppem_uniform(uint32_t ppem_26_6);
int snail_true_type_hint_context_init(const SnailAllocator *alloc,
                                      const SnailTextAtlas *atlas,
                                      SnailTrueTypeHintContext **out);
void snail_true_type_hint_context_deinit(SnailTrueTypeHintContext *context);
void snail_true_type_hint_context_reset_for_atlas(SnailTrueTypeHintContext *context,
                                                 const SnailTextAtlas *atlas);
int snail_true_type_hint_context_prepare_size(SnailTrueTypeHintContext *context,
                                             size_t face_index,
                                             SnailTrueTypeHintPpem ppem);
int snail_true_type_hint_context_prepare_run(SnailTrueTypeHintContext *context,
                                            const SnailAllocator *alloc,
                                            const SnailShapedText *shaped,
                                            SnailRange glyphs,
                                            SnailTrueTypeHintPpem ppem,
                                            SnailTrueTypePreparedHintRun **out);
void snail_true_type_prepared_hint_run_deinit(SnailTrueTypePreparedHintRun *run);
void snail_true_type_prepared_hint_run_stats(const SnailTrueTypePreparedHintRun *run,
                                             SnailTrueTypeHintRunStats *out);
int snail_text_blob_init_from_prepared_hinted_run(const SnailAllocator *alloc,
                                                  const SnailTrueTypePreparedHintRun *run,
                                                  SnailTextPlacement placement,
                                                  const float color[4],
                                                  SnailTextBlob **out);

int snail_text_blob_init_from_shaped(const SnailAllocator *alloc,
                                     const SnailTextAtlas *atlas,
                                     const SnailShapedText *shaped,
                                     SnailTextAppendOptions options,
                                     SnailTextBlob **out);
int snail_text_blob_init_text(const SnailAllocator *alloc,
                              const SnailTextAtlas *atlas,
                              SnailFontStyle style,
                              const char *text,
                              size_t text_len,
                              SnailTextAppendOptions options,
                              SnailTextBlob **out);
void snail_text_blob_deinit(SnailTextBlob *blob);
size_t snail_text_blob_glyph_count(const SnailTextBlob *blob);
int snail_text_blob_rebound(const SnailAllocator *alloc,
                            const SnailTextBlob *blob,
                            const SnailTextAtlas *atlas,
                            SnailTextBlob **out);

/* Images */

int snail_image_init_srgba8(const SnailAllocator *alloc,
                            uint32_t width,
                            uint32_t height,
                            const uint8_t *pixels,
                            size_t pixel_len,
                            SnailImage **out);
void snail_image_deinit(SnailImage *image);
uint32_t snail_image_width(const SnailImage *image);
uint32_t snail_image_height(const SnailImage *image);
void snail_image_upload_footprint(const SnailImage *image,
                                  SnailResourceFootprint *out);

/* Paths and path pictures */

int snail_path_init(const SnailAllocator *alloc, SnailPath **out);
void snail_path_deinit(SnailPath *path);
void snail_path_reset(SnailPath *path);
bool snail_path_is_empty(const SnailPath *path);
bool snail_path_bounds(const SnailPath *path, SnailBBox *out);
int snail_path_move_to(SnailPath *path, float x, float y);
int snail_path_line_to(SnailPath *path, float x, float y);
int snail_path_quad_to(SnailPath *path, float cx, float cy, float x, float y);
int snail_path_cubic_to(SnailPath *path, float c1x, float c1y,
                        float c2x, float c2y, float x, float y);
int snail_path_close(SnailPath *path);
int snail_path_add_rect(SnailPath *path, SnailRect rect);
int snail_path_add_rect_reversed(SnailPath *path, SnailRect rect);
int snail_path_add_rounded_rect(SnailPath *path, SnailRect rect, float radius);
int snail_path_add_rounded_rect_reversed(SnailPath *path,
                                         SnailRect rect,
                                         float radius);
int snail_path_add_ellipse(SnailPath *path, SnailRect rect);
int snail_path_add_ellipse_reversed(SnailPath *path, SnailRect rect);

int snail_path_picture_builder_init(const SnailAllocator *alloc, SnailPathPictureBuilder **out);
void snail_path_picture_builder_deinit(SnailPathPictureBuilder *builder);
size_t snail_path_picture_builder_shape_count(const SnailPathPictureBuilder *builder);
SnailShapeMark snail_path_picture_builder_mark(const SnailPathPictureBuilder *builder);
int snail_path_picture_builder_range_from(const SnailPathPictureBuilder *builder,
                                          SnailShapeMark mark,
                                          SnailRange *out);
int snail_path_picture_builder_range_between(const SnailPathPictureBuilder *builder,
                                             SnailShapeMark start,
                                             SnailShapeMark end,
                                             SnailRange *out);
int snail_path_picture_builder_add_path(SnailPathPictureBuilder *builder,
                                        const SnailPath *path,
                                        const SnailFillStyle *fill,
                                        const SnailStrokeStyle *stroke,
                                        SnailTransform2D transform);
int snail_path_picture_builder_add_filled_path(SnailPathPictureBuilder *builder,
                                               const SnailPath *path,
                                               SnailFillStyle fill,
                                               SnailTransform2D transform);
int snail_path_picture_builder_add_stroked_path(SnailPathPictureBuilder *builder,
                                                const SnailPath *path,
                                                SnailStrokeStyle stroke,
                                                SnailTransform2D transform);
int snail_path_picture_builder_add_rect(SnailPathPictureBuilder *builder,
                                        SnailRect rect,
                                        const SnailFillStyle *fill,
                                        const SnailStrokeStyle *stroke,
                                        SnailTransform2D transform);
int snail_path_picture_builder_add_rounded_rect(SnailPathPictureBuilder *builder,
                                                SnailRect rect,
                                                const SnailFillStyle *fill,
                                                const SnailStrokeStyle *stroke,
                                                float corner_radius,
                                                SnailTransform2D transform);
int snail_path_picture_builder_add_ellipse(SnailPathPictureBuilder *builder,
                                           SnailRect rect,
                                           const SnailFillStyle *fill,
                                           const SnailStrokeStyle *stroke,
                                           SnailTransform2D transform);
int snail_path_picture_builder_freeze(const SnailPathPictureBuilder *builder,
                                      const SnailAllocator *alloc,
                                      const SnailAllocator *scratch_alloc,
                                      SnailPathPicture **out);
void snail_path_picture_deinit(SnailPathPicture *picture);
size_t snail_path_picture_shape_count(const SnailPathPicture *picture);
void snail_path_picture_upload_footprint(const SnailPathPicture *picture,
                                         SnailResourceFootprint *out);

/* Scene and resources */

/*
 * `SnailTextDraw` and `SnailPathPictureDraw` copy one optional override value
 * into scene-owned storage when `has_override` is true. `snail_scene_reset`
 * is the explicit lifetime boundary for that copied storage and the command
 * list. Blob, picture, and resource handles are borrowed; keep them alive
 * until the scene is reset or destroyed.
 */
int snail_scene_init(const SnailAllocator *alloc, SnailScene **out);
void snail_scene_deinit(SnailScene *scene);
void snail_scene_reset(SnailScene *scene);
size_t snail_scene_command_count(const SnailScene *scene);
int snail_scene_add_text_draw(SnailScene *scene,
                              SnailTextDraw draw);
int snail_scene_add_path_picture_draw(SnailScene *scene,
                                      SnailPathPictureDraw draw);

int snail_resource_manifest_init(const SnailAllocator *alloc, size_t capacity, SnailResourceManifest **out);
void snail_resource_manifest_deinit(SnailResourceManifest *set);
void snail_resource_manifest_reset(SnailResourceManifest *set);
size_t snail_resource_manifest_count(const SnailResourceManifest *set);
size_t snail_resource_manifest_capacity(const SnailResourceManifest *set);
int snail_text_resource_keys_for_blob(SnailResourceKey atlas_key,
                                      SnailResourceKey blob_key,
                                      const SnailTextBlob *blob,
                                      SnailTextResourceKeys *out);
int snail_resource_manifest_put_text_blob(SnailResourceManifest *set,
                                          SnailTextResourceKeys resources,
                                          const SnailTextBlob *blob);
int snail_resource_manifest_put_text_blob_options(SnailResourceManifest *set,
                                                  SnailTextResourceKeys resources,
                                                  const SnailTextBlob *blob,
                                                  int atlas_capacity);
int snail_resource_manifest_put_text_blob_reserved(SnailResourceManifest *set,
                                                   SnailTextResourceKeys resources,
                                                   const SnailTextBlob *blob,
                                                   uint32_t reserved_pages);
int snail_resource_manifest_put_path_picture(SnailResourceManifest *set,
                                        SnailResourceKey key,
                                        const SnailPathPicture *picture);
int snail_resource_manifest_put_path_picture_options(SnailResourceManifest *set,
                                                SnailResourceKey key,
                                                const SnailPathPicture *picture,
                                                int atlas_capacity);
int snail_resource_manifest_put_path_picture_reserved(SnailResourceManifest *set,
                                                 SnailResourceKey key,
                                                 const SnailPathPicture *picture,
                                                 uint32_t reserved_pages);
int snail_resource_manifest_put_image(SnailResourceManifest *set,
                                 SnailResourceKey key,
                                 const SnailImage *image);
int snail_resource_manifest_estimate_upload_footprint(const SnailResourceManifest *set,
                                                 SnailResourceFootprint *out);

/* PreparedResources owns CPU-side prepared data. GPU residency is owned by the
 * renderer resource cache; deinit/retire releases this handle's manifest and
 * CPU snapshot, but does not immediately evict renderer-owned GPU cache
 * entries. */
void snail_prepared_resources_deinit(SnailPreparedResources *prepared);
bool snail_prepared_resources_stamp_for_key(const SnailPreparedResources *prepared,
                                            SnailResourceKey key,
                                            SnailResourceStamp *out);
int snail_prepared_scene_init(const SnailAllocator *alloc,
                              const SnailPreparedResources *prepared,
                              const SnailScene *scene,
                              SnailPreparedScene **out);
void snail_prepared_scene_deinit(SnailPreparedScene *scene);
size_t snail_prepared_scene_word_count(const SnailPreparedScene *scene);
size_t snail_prepared_scene_segment_count(const SnailPreparedScene *scene);

int snail_prepared_resource_retirement_queue_init(const SnailAllocator *alloc,
                                                  SnailPreparedResourceRetirementQueue **out);
void snail_prepared_resource_retirement_queue_deinit(SnailPreparedResourceRetirementQueue *queue);
void snail_prepared_resource_retirement_queue_sweep(SnailPreparedResourceRetirementQueue *queue);
int snail_prepared_resource_retirement_queue_retire(SnailPreparedResourceRetirementQueue *queue,
                                                    SnailPreparedResources *prepared);

/* Caller-buffered draw records */

size_t snail_draw_list_estimate_word_count(const SnailScene *scene);
size_t snail_draw_list_estimate_segment_count(const SnailScene *scene);
int snail_draw_list_init(const SnailAllocator *alloc,
                         size_t word_capacity,
                         size_t segment_capacity,
                         SnailDrawList **out);
void snail_draw_list_deinit(SnailDrawList *list);
void snail_draw_list_reset(SnailDrawList *list);
size_t snail_draw_list_word_count(const SnailDrawList *list);
size_t snail_draw_list_word_capacity(const SnailDrawList *list);
size_t snail_draw_list_segment_count(const SnailDrawList *list);
size_t snail_draw_list_segment_capacity(const SnailDrawList *list);
const uint32_t *snail_draw_list_words(const SnailDrawList *list);
int snail_draw_list_add_scene(SnailDrawList *list,
                              const SnailPreparedResources *prepared,
                              const SnailScene *scene);

/* Custom text coverage records */

size_t snail_text_coverage_records_word_capacity_for_blob(const SnailTextBlob *blob);
int snail_text_coverage_records_init(const SnailAllocator *alloc,
                                     size_t word_capacity,
                                     SnailTextCoverageRecords **out);
void snail_text_coverage_records_deinit(SnailTextCoverageRecords *records);
void snail_text_coverage_records_reset(SnailTextCoverageRecords *records);
size_t snail_text_coverage_records_word_count(const SnailTextCoverageRecords *records);
size_t snail_text_coverage_records_glyph_count(const SnailTextCoverageRecords *records);
uint32_t snail_text_coverage_records_layer_window_base(const SnailTextCoverageRecords *records);
const uint32_t *snail_text_coverage_records_words(const SnailTextCoverageRecords *records);
int snail_text_coverage_records_build_local(SnailTextCoverageRecords *records,
                                            const SnailPreparedResources *prepared,
                                            const SnailTextBlob *blob,
                                            SnailTextResourceKeys resources,
                                            SnailTransform2D transform);
int snail_text_coverage_records_draw_state(const SnailTextCoverageRecords *records,
                                           SnailDrawState state,
                                           SnailCoverageDrawState *out);
bool snail_text_coverage_records_valid_for(const SnailTextCoverageRecords *records,
                                           const SnailPreparedResources *prepared);

/* Backend hook for custom text coverage shaders. */

int snail_coverage_backend_init(SnailRenderer *renderer,
                                const SnailPreparedResources *prepared,
                                SnailCoverageBackend **out);
void snail_coverage_backend_deinit(SnailCoverageBackend *backend);
int snail_coverage_backend_draw_coverage(SnailCoverageBackend *backend,
                                         const SnailTextCoverageRecords *records);
int snail_coverage_backend_draw_words(SnailCoverageBackend *backend,
                                      const uint32_t *words,
                                      size_t word_count);

/* Renderer
 *
 * Construct renderers through backend headers such as snail_cpu.h,
 * snail_gl33.h, snail_gl44.h, snail_gles30.h, and snail_vulkan.h, then use this erased renderer
 * handle for shared operations.
 */

void snail_renderer_deinit(SnailRenderer *renderer);
/* Static, null-terminated backend name. The returned pointer is borrowed. */
const char *snail_renderer_backend_name(const SnailRenderer *renderer);
void snail_renderer_resource_cache_stats(SnailRenderer *renderer,
                                         SnailResourceCacheStats *out);
void snail_renderer_reset_resource_cache(SnailRenderer *renderer);
int snail_renderer_upload_resources_blocking(SnailRenderer *renderer,
                                             const SnailAllocator *alloc,
                                             const SnailResourceManifest *set,
                                             SnailPreparedResources **out);
int snail_renderer_plan_resource_upload(SnailRenderer *renderer,
                                        const SnailAllocator *alloc,
                                        const SnailPreparedResources *current,
                                        const SnailResourceManifest *next_set,
                                        SnailResourceUploadPlan **out);
void snail_resource_upload_plan_deinit(SnailResourceUploadPlan *plan);
void snail_resource_upload_plan_summary(const SnailResourceUploadPlan *plan,
                                        SnailResourceUploadPlanSummary *out);
bool snail_resource_upload_plan_changed_key(const SnailResourceUploadPlan *plan,
                                            size_t index,
                                            SnailResourceKey *out);
int snail_renderer_begin_resource_upload(SnailRenderer *renderer,
                                         const SnailAllocator *alloc,
                                         const SnailResourceUploadPlan *plan,
                                         SnailPendingResourceUpload **out);
void snail_pending_resource_upload_deinit(SnailPendingResourceUpload *pending);
int snail_pending_resource_upload_record(SnailPendingResourceUpload *pending,
                                         size_t budget_bytes);
int snail_pending_resource_upload_record_checked(SnailPendingResourceUpload *pending,
                                                 size_t budget_bytes,
                                                 bool allow_cache_rebuilds);
bool snail_pending_resource_upload_ready(SnailPendingResourceUpload *pending,
                                         bool ready);
bool snail_pending_resource_upload_ready_now(SnailPendingResourceUpload *pending);
int snail_pending_resource_upload_publish(SnailPendingResourceUpload *pending,
                                          SnailPreparedResources **out);
int snail_renderer_draw(SnailRenderer *renderer,
                        const SnailPreparedResources *prepared,
                        const SnailDrawList *list,
                        SnailDrawState state);
int snail_renderer_draw_pass(SnailRenderer *renderer,
                             const SnailPreparedResources *prepared,
                             const SnailDrawList *list,
                             SnailDrawPass pass);
int snail_renderer_draw_prepared(SnailRenderer *renderer,
                                 const SnailPreparedResources *prepared,
                                 const SnailPreparedScene *scene,
                                 SnailDrawState state);
int snail_renderer_draw_prepared_pass(SnailRenderer *renderer,
                                      const SnailPreparedResources *prepared,
                                      const SnailPreparedScene *scene,
                                      SnailDrawPass pass);

/* Features and constants */

bool snail_harfbuzz_available(void);
size_t snail_text_words_per_glyph(void);
size_t snail_text_words_per_vertex(void);
size_t snail_text_vertices_per_glyph(void);
size_t snail_path_words_per_shape(void);
size_t snail_path_words_per_vertex(void);
size_t snail_path_vertices_per_shape(void);
SnailMat4 snail_mat4_identity(void);

#ifdef __cplusplus
}
#endif

#endif /* SNAIL_H */
